### ISSUE TITLE
 examples  all part of cesium was error

### ISSUE THREAD

**Issue by qq897425998** [openlayers/ol-cesium#1010]
I cannot show  examples  all part of cesium was error

**Comment by qq897425998** [comment]
console show  error 
cesiumWorkerBootstrapper.js:26 Uncaught TypeError: Cannot read properties of undefined (reading 'baseUrl')
    at cesiumWorkerBootstrapper.js:26:168
    at Object.execCb (cesiumWorkerBootstrapper.js:31:11809)
    at c.check (cesiumWorkerBootstrapper.js:31:5271)
    at c.enable (cesiumWorkerBootstrapper.js:31:7878)
    at c.init (cesiumWorkerBootstrapper.js:31:4326)
    at cesiumWorkerBootstrapper.js:31:10189
    at setTimeout (cesiumWorkerBootstrapper.js:26:202)
    at req.nextTick (cesiumWorkerBootstrapper.js:31:12475)
    at Object.o [as require] (cesiumWorkerBootstrapper.js:31:10128)
    at requirejs (cesiumWorkerBootstrapper.js:31:12374)

**Comment by gberaudo** [comment]
Hi @qq897425998 , see https://github.com/openlayers/ol-cesium/pull/1004.
I ran "npm start" there it worked.
How do you get this error?

**Comment by gberaudo** [comment]
Hi, please try again and if the issue still occurs reopen with the detailed steps you followed.
